language: python

arch:
  - amd64
  - ppc64le
python:
  - "3.12.2"
jobs:
  exclude:
   - arch : ppc64le
     python : pypy
   - arch : ppc64le
     python : pypy3

sudo: false

install:
  - pip install .
  - pip install -r requirements.txt